### LLM completion
GRPC {{llm_host}}/llm.LLM/Completion

{
  "prompt": "What is the most populated city in Colombia?"
}

### LLM completion stream
GRPC {{llm_host}}/llm.LLM/CompletionStream

{
  "prompt": "What is the most populated city in Colombia?"
}

### LLM chat completion
GRPC {{llm_host}}/llm.LLM/ChatCompletion

{
  "messages": [
    {
      "role": "ROLE_USER",
      "content": "What is the most populated city in Colombia?"
    },
    {
      "role": "ROLE_LLM",
      "content": "The most populated city in Colombia is Bogotá, with a population of over 7 million people."
    },
    {
      "role": "ROLE_USER",
      "content": "Thanks! I'm planning a trip there and wanted to know more about the local attractions."
    }
  ]
}

### LLM chat completion stream
GRPC {{llm_host}}/llm.LLM/ChatCompletionStream

{
  "messages": [
    {
      "role": "ROLE_USER",
      "content": "What is the most populated city in Colombia?"
    },
    {
      "role": "ROLE_LLM",
      "content": "The most populated city in Colombia is Bogotá, with a population of over 7 million people."
    },
    {
      "role": "ROLE_USER",
      "content": "Thanks! I'm planning a trip there and wanted to know more about the local attractions."
    }
  ]
}

### AI sign up
GRPC {{ai_host}}/ai.Authenticator/SignUp

{
  "username": "username",
  "password": "password"
}

### AI sign in
GRPC {{ai_host}}/ai.Authenticator/SignIn

{
  "username": "username",
  "password": "password"
}
