FROM ubuntu:22.04 as builder

ARG AI_HOST
ARG AI_WEB_HOST
ARG AI_PORT
ARG AI_WEB_PORT
ARG AI_SECURE

ARG FLUTTER_SDK=/opt/flutter
ARG FLUTTER_VERSION=3.19.2

RUN apt update && apt install -y git curl unzip
RUN git clone --depth 1 --branch $FLUTTER_VERSION https://github.com/flutter/flutter.git $FLUTTER_SDK
ENV PATH="$PATH:$FLUTTER_SDK/bin"
RUN flutter doctor -v

WORKDIR /ui
COPY ./ui .

RUN flutter clean
RUN flutter pub get
RUN flutter build web --release \
    --dart-define AI_HOST=$AI_HOST \
    --dart-define AI_WEB_HOST=$AI_WEB_HOST \
    --dart-define AI_PORT=$AI_PORT \
    --dart-define AI_WEB_PORT=$AI_WEB_PORT \
    --dart-define AI_SECURE=$AI_SECURE

FROM nginx:alpine3.18
COPY --from=builder /ui/build/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
